---
abstract: 'release tests for synopses'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100660'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-SynopsisTests
provides:
  Dist::Zilla::Plugin::SynopsisTests:
    file: lib/Dist/Zilla/Plugin/SynopsisTests.pm
    version: 1.100700
requires:
  Dist::Zilla::Plugin::InlineFiles: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Moose: 0
  Test::More: 0
  Test::Synopsis: 0
  perl: 5.008
resources:
  repository: http://github.com/hanekomu/Dist-Zilla-Plugin-SynopsisTests
version: 1.100700
